ToDoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base'))
]

base/urls.py
from django.urls import path
from .views import *
from .models import * 
from django.contrib.auth.views import LogoutView


app_name = 'base'
urlpatterns = [
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(next_page= 'base:login'), name='logout'), 
    path('signup', RegisterPage.as_view(), name="signup"), 
    path('', TaskList.as_view(), name='tasks'), 
    path('create-task', TaskCreate.as_view(), name='create-task'), 
    path('update-task/<int:pk>', TaskUpdate.as_view(), name="update-task"), 
    path('delete-task/<int:pk>', TaskDelete.as_view(), name="delete-task"), 
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import TextField


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering =['complete']

        

base/views.py
from django.db.models import fields
from base.models import Task
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
# Create your views here.


class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    def get_success_url(self) :
        return reverse_lazy('base:tasks')


class RegisterPage(FormView):
    template_name = 'base/signup.html' 
    form_class = UserCreationForm
    success_url = reverse_lazy('base:tasks')
    
    def form_valid(self, form): 
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('base:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name ='tasks'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith  =search_input)
        context['search_input'] = search_input
        return context



class TaskDetail(LoginRequiredMixin,DetailView):
    model = Task
    template_name ='base/task.html'




class TaskCreate(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)



class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('base:tasks')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('base:tasks')

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
        <p>Don't have an account? <a href="{% url 'base:signup' %}">Signup</a></p>
    </form>
</div>




{% endblock content %}

base/templates/base/main.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        body{
           background-color: #FAFAFA;
           font-family: cursive;
           padding-top: 50px;
        }
        
         h2,h3,h4,h5, h6{
            font-family: 'Relway', sans-serif;
           
        }
        h1{
            font-family: 'Relway', sans-serif;
            margin-left: 10px;
        }
        h1#welcome{
            font-family: 'Relway', sans-serif;
            margin-left: 0;
        }
        a, p{
            color: #000000;
        }

        .container{
            max-width: 550px;
            margin: auto;
            background-color: #fff;
            -webkit-box-shadow : 2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow:  2px 2px 13px -4px rgba(0,0,0,0.21);
        }
        .header-bar{
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #d28a77 0%, #ca5f57 43%, #a74f47 90%);

        }
        .header-bar a{
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        .task-wrapper{
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #fff;
            border-top: 1px solid rgb(226, 226, 226);
        }
        .task-title{
            display: flex;
        }
        .task-title a{
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }
        .task-complete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }
        .task-incomplete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(73, 143, 73);
            
            border-radius: 50%;
        }
        .delete-link{
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
        }
        #search-add-wrapper{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }
        #add-link{
            color:#EB796F;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;

        }
        @media screen and (max-width:320px) {
            #search-add-wrapper {
                padding: 10px;
            }
        }

        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        ::placeholder {
            font-weight: 300;
            opacity: 0.5;
        }

        .button {
            border: 1px solid #757575;
            background-color: #FFF;
            color: #EB796F;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            font-family: 'Roboto', sans-serif;
            font-weight: 500;
        }

        .card-body {
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

base/templates/base/signup.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Signup</h1>
</div>
<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label >{{form.username.label}}</label>
        {{form.username}}

        <label >{{form.password1.label}}</label>
        {{form.password1}}

        <label >{{form.password2.label}}</label>
        {{form.password2}}

        <input style="margin-top:10px;" class="button" type="submit" value="Signup">
    </form>
    <p>Already have an account? <a href="{% url 'base:login'%}">Login</a></p>
</div>

{% endblock content %}

base/templates/base/task.html
<h1>Task: {{task.title}} </h1>

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'base:tasks' %}">&#8592 Back</a>
</div>
<div class="card-body">
    <form method = "POST">
        {% csrf_token %}
        <p>Are you sure you wanna delete this task? "{{task}}"</p>
        <input type="submit" value="Delete" class="button">
    </form>
</div>

{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <a href="{% url 'base:tasks' %}">&#8592 Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
            {{form.as_p}}
            <input class="button"type="submit"  value="Update">
        </form>

</div>
{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% block content %}

    <div class="header-bar">
        <div>
            <h1 id="welcome">Hello {{request.user|title}}</h1>
            <h3 style="margin: 0;">You have <i>{{count}}</i> incomplete task{{count|pluralize:"s"}}</h3>
        </div>

        {% if request.user.is_authenticated %}
        <a href="{% url 'base:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'base:login' %}">Login</a>
        {% endif %}
    </div>


    <div id="search-add-wrapper">
        <form method="GET" style="margin-top:20px; display:flex;">
            <input type="text" name="search-area" value={{search_input}}>
            <input class="button" type="submit" value="Search">
        </form>
        <a id="add-link" href="{% url 'base:create-task' %}">&#x2b;</a>
    </div>

   
  
    <div class="task-items-wrapper">
        {% for task in tasks %}
            <div class="task-wrapper">
                {% if task.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"> </div>
                            <i><s><a href="{% url 'base:update-task' task.id %}">{{task.title}}</a></s></i>
                        </div>
                        <a class="delete-link" href="{% url 'base:delete-task' task.id %}">&#215;</a>
                {% else %}
                <div class="task-title">
                    <div class="task-incomplete-icon"> </div>
                        <a href="{% url 'base:update-task' task.id %}">{{task.title}}</a>
                    </div>
                    <a class="delete-link" href="{% url 'base:delete-task' task.id %}">&#215;</a>
                {% endif %}
                

            </div>
        {% empty %}
            <h3>You have no tasks</h3>
        {% endfor %}
    </div>

  

{% endblock content %}